echo "$(cat media/css/dataTables.bootstrap5.min.css)"
echo "$(cat extensions/AutoFill/css/autoFill.bootstrap5.min.css)"
echo "$(cat extensions/Buttons/css/buttons.bootstrap5.min.css)"
echo "$(cat extensions/Scroller/css/scroller.bootstrap5.min.css)"
echo "$(cat extensions/Select/css/select.bootstrap5.min.css)"